# Generated by Django 4.0.3 on 2024-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='default_id', max_length=50, unique=True),
        ),
    ]
