# Generated by Django 4.0.3 on 2024-07-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='xxx', max_length=50, unique=True),
        ),
    ]
