# Generated by Django 4.0.3 on 2024-07-18 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_quantity_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
